apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework
  labels:
    app: framework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: framework
  template:
    metadata:
      labels:
        app: framework
    spec:
      containers:
      - name: framework
        image: framework:v1.0.0
        imagePullPolicy: Never # Use the local image
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10